version: 2
jobs:
  build:
    docker:
      - image: abaez/luarocks
    steps:
      - run:
          name: Install APKs
          command: apk add --no-cache --update git
      - checkout
      - run:
          name: Install rocks
          command: luarocks install busted && 
                   luarocks install luafilesystem && 
                   luarocks install serpent
      - run:
          name: Run unit tests
          command: busted -v
